### ISSUE TITLE
I made a Morse Code guide for everyone's favorite item, the Marconi Receiver! (should probably be invisible because this is the height of spammable guides)

### ISSUE THREAD

**Issue by Non-C** [twohoursonelife/junior#20]
Morse Code
The Marconi receiver uses Morse Code to communicate.  Here is a quick guide of the letters:

A: .-
B: .---
C: -.-.
D: -...
E: .
F: ..-.
G: --.
H: ....
I: ..
J: .---
K: .-.
L: .-..
M: --
N: -.
O: ---
P: .--.
Q: --.-
R: .-.
S: ...
T: -
U: ..-
V: ...-
W: .--
X: .--.
Y: -.--
Z: --..

**Comment by connorhsm** [comment]
Going to pass on this one. No value added beyond a Google search.
