### ISSUE TITLE
Updated yum guides

### ISSUE THREAD

**Issue by Non-C** [twohoursonelife/junior#29]
Yum Chaining

Yum is possibly the most important mechanic to learn in 2HOL.  To yum chain allows for food security and the ability to go much, much longer without eating.

When you hold a food, your character will say either "YUM" or "MEH".  Every food is yum once per life, and after it is eaten once during a life, it will be meh for the remainder of it.  Always strive to eat yum foods because they give bonuses.  This means that you should always strive to eat variety, and not rely on a single food source.

Every time you eat a yum food, your "LEVEL" goes up by 1.  Your level matches the bonus food you get for eating that yum food.  "BONUS" is extra food that isn't in a box.  Every food has a set amount of boxes it will fill up, but only yum foods will add to your level and bonus.  Your bonus number counts down before your food boxes.  Meh foods will only give you base value of the food, which can be good in a pinch, but doesn't really fill you up.

If you keep eating yum foods - "chaining" them, then eventually your bonus will far surpass your food meter, allowing you to go long times without needing to eat.

For advice on cravings, another yum related feature, type /craving

Cravings

Cravings are a more advanced feature to the simple yum chain.  After age 10, the name of a random food will appear above your food meter, followed by the number of levels that such food will increase your "LEVEL" by.  Even if you have already eaten the food previously and it would've been meh, cravings will still offer their bonuses.

Cravings are designed to push you to advance or look into interesting foods you wouldn't make otherwise.  The types of food that appear as your craving are determined by the level of complexity of foods eaten by members of your family.  If you are an eve, your first few cravings will be simple forgeables, such as apples, and will slowly progress to being more complicated, such as bread.

You can never lose your craving once you have it, and any children you have will inherit the craving. Each family has a unique craving path, so your next craving will be the same as your children's next craving.

**Comment by TanyaPegasus** [comment]
We discussed this and realised a few edits were needed due to changes in yum mechanics over the last year.
There are 2 options below. The first one keeps a little more of the original structure, while the second shortens it up a little and puts the most important detail front and centre. I think. 

> Yum is possibly the most important mechanic to learn in 2HOL. To yum chain allows for food security and the ability to go much longer without eating.
> 
> When you hold a food, your character will say either "YUM" or "MEH". Every food is yum once per life, and then becomes meh for the remainder of that life. Always strive to eat yum foods because they give bonuses. This means that you should eat variety, and not rely on a single food source.
> 
> You have a “LEVEL” and a “BONUS”. Your "LEVEL" goes up by 1 each time you eat a yum food. Your "BONUS" is like extra food that isn't in a box and counts down before your food boxes. Every food has a base value and an additional bonus value. When you eat a yum food, the base value fills your boxes, and your bonus value increases. You also receive your “LEVEL” as even more bonus.
> 
> Meh foods will give you their base value and fill the bonus into any empty boxes. Any bonus remaining after the boxes are filled will be lost, so eating meh can be good in a pinch, but doesn't really fill you up.
> 
> If you keep eating yum foods - "chaining" them, then eventually your bonus will far surpass your food meter, allowing you to go long times without needing to eat.
> 
> For advice on cravings, another yum related feature, type /craving
> 


-
-
-

> Yum is possibly the most important mechanic to learn in 2HOL. If you keep eating yum foods - "chaining" them, then eventually your bonus will far surpass your food meter, allowing you to go long times without needing to eat.
> 
> When you hold a food, your character will say either "YUM" or "MEH". Every food is yum once per life, and then becomes meh for the remainder of that life. Always strive to eat yum foods because they give bonuses. This means that you should eat variety, and not rely on a single food source.
> 
> You have a “LEVEL” and a “BONUS”. Your "LEVEL" goes up by 1 each time you eat a yum food. Your "BONUS" is like extra food that isn't in a box and counts down before your food boxes. Every food has a base value and an additional bonus value. When you eat a yum food, the base value fills your boxes, and your bonus value increases. You also receive your “LEVEL” as even more bonus.
> 
> Meh foods will give you their base value and fill the bonus into any empty boxes. Any bonus remaining after the boxes are filled will be lost, so eating meh can be good in a pinch, but doesn't really fill you up.
> 
> For advice on cravings, another yum related feature, type /craving
>
