### ISSUE TITLE
Uno keeps yelling at me that the cookie command is wrong

### ISSUE THREAD

**Issue by Non-C** [twohoursonelife/junior#8]
The cookie command says to use a flint chip instead of the newly needed flint knife to harvest ripe wheat.  Please change this.  It doesn't annoy me, but Uno pinging me whenever she sees it annoys me.

**Comment by lucanLepus** [comment]
To further flesh out this very important issue.
Step 1 states:
> This is done by using a sharp stone or flint chip on some ripe wheat.

Step 2 states:

> Once it dries, put it in a bowl and grind it with a flint chip to become corn kernels.

Step 3 states:

> Use a sharp stone or flint chip to harvest some sugarcane.

i suggest substituting _**any knife**_ for any occurence of _**(a) flint chip**_

**Comment by connorhsm** [comment]
Released as version 1.2.0.  Will be live by the time you read this.
Thank you both for your significant contributions to this endeavour.
